import readline from 'readline';
import { execSync, spawnSync } from 'child_process';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const PROJECT_ROOT = join(import.meta.dirname, '..');
const ENV_FILE = join(PROJECT_ROOT, '.env');

// ANSI colors
const green = (s: string) => `\x1b[32m${s}\x1b[0m`;
const yellow = (s: string) => `\x1b[33m${s}\x1b[0m`;
const red = (s: string) => `\x1b[31m${s}\x1b[0m`;
const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;

const pass = (msg: string) => console.log(green(`  [ok] ${msg}`));
const warn = (msg: string) => console.log(yellow(`  [!!] ${msg}`));
const fail = (msg: string) => console.log(red(`  [xx] ${msg}`));

function banner(): void {
  console.log(`
 ${bold('██████╗██╗      █████╗ ██╗   ██╗██████╗ ███████╗')}
 ${bold('██╔════╝██║     ██╔══██╗██║   ██║██╔══██╗██╔════╝')}
 ${bold('██║     ██║     ███████║██║   ██║██║  ██║█████╗')}
 ${bold('██║     ██║     ██╔══██║██║   ██║██║  ██║██╔══╝')}
 ${bold('╚██████╗███████╗██║  ██║╚██████╔╝██████╔╝███████╗')}
 ${bold(' ╚═════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝╚══════╝')}
 ${bold('██████╗██╗      █████╗ ██╗    ██╗')}
 ${bold('██╔════╝██║     ██╔══██╗██║    ██║')}
 ${bold('██║     ██║     ███████║██║ █╗ ██║')}
 ${bold('██║     ██║     ██╔══██║██║███╗██║')}
 ${bold('╚██████╗███████╗██║  ██║╚███╔███╔╝')}
 ${bold(' ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝')}

 ${dim('Setup Wizard')}
`);
}

function checkPrerequisites(): boolean {
  let ok = true;

  // Check Node version
  const nodeVersion = process.version;
  const major = parseInt(nodeVersion.slice(1).split('.')[0], 10);
  if (major >= 20) {
    pass(`Node.js ${nodeVersion}`);
  } else {
    fail(`Node.js ${nodeVersion} -- need >= 20`);
    ok = false;
  }

  // Check claude CLI
  const claudeResult = spawnSync('which', ['claude'], { encoding: 'utf-8' });
  if (claudeResult.status === 0) {
    const claudePath = claudeResult.stdout.trim();
    pass(`Claude CLI found at ${claudePath}`);

    // Try getting version
    const versionResult = spawnSync('claude', ['--version'], {
      encoding: 'utf-8',
      timeout: 5000,
    });
    if (versionResult.status === 0) {
      const ver = versionResult.stdout.trim().split('\n')[0];
      pass(`Claude CLI version: ${ver}`);
    }
  } else {
    fail('Claude CLI not found -- install from https://docs.anthropic.com/en/docs/claude-code');
    ok = false;
  }

  return ok;
}

function createInterface(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise(resolve => {
    rl.question(question, answer => resolve(answer.trim()));
  });
}

async function collectConfig(rl: readline.Interface): Promise<Record<string, string>> {
  const config: Record<string, string> = {};

  console.log(bold('\n  Telegram Configuration\n'));

  config.TELEGRAM_BOT_TOKEN = await ask(
    rl,
    '  Telegram Bot Token (from @BotFather): '
  );
  if (!config.TELEGRAM_BOT_TOKEN) {
    fail('Bot token is required');
    process.exit(1);
  }
  pass('Bot token saved');

  config.ALLOWED_CHAT_ID = await ask(
    rl,
    dim('  Allowed Chat ID (leave blank to set later): ')
  );
  if (config.ALLOWED_CHAT_ID) {
    pass(`Chat ID: ${config.ALLOWED_CHAT_ID}`);
  } else {
    warn('Chat ID not set -- send /chatid to the bot after starting');
  }

  console.log(bold('\n  Optional API Keys\n'));

  config.GROQ_API_KEY = await ask(
    rl,
    dim('  Groq API Key (for voice transcription, blank to skip): ')
  );
  if (config.GROQ_API_KEY) {
    pass('Groq API key saved');
  } else {
    warn('Groq not configured -- voice notes will be unsupported');
  }

  config.GOOGLE_API_KEY = await ask(
    rl,
    dim('  Google API Key (for video analysis, blank to skip): ')
  );
  if (config.GOOGLE_API_KEY) {
    pass('Google API key saved');
  } else {
    warn('Google not configured -- video analysis will be unsupported');
  }

  return config;
}

function writeEnvFile(config: Record<string, string>): void {
  const lines = [
    '# ClaudeClaw Configuration',
    `# Generated by setup wizard on ${new Date().toISOString()}`,
    '',
    '# --- Required -----------------------------------------------',
    `TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN || ''}`,
    `ALLOWED_CHAT_ID=${config.ALLOWED_CHAT_ID || ''}`,
    '',
    '# --- Voice (STT) --------------------------------------------',
    `GROQ_API_KEY=${config.GROQ_API_KEY || ''}`,
    '',
    '# --- Video Analysis ------------------------------------------',
    `GOOGLE_API_KEY=${config.GOOGLE_API_KEY || ''}`,
    '',
    '# --- Optional ------------------------------------------------',
    'LOG_LEVEL=info',
    'NODE_ENV=production',
  ];
  writeFileSync(ENV_FILE, lines.join('\n') + '\n');
  pass(`.env written to ${ENV_FILE}`);
}

function openEditor(): void {
  const claudeMd = join(PROJECT_ROOT, 'CLAUDE.md');
  const editor = process.env.EDITOR || 'nano';

  console.log(bold('\n  Personalize CLAUDE.md\n'));
  console.log(dim(`  Opening ${claudeMd} in ${editor}...`));
  console.log(dim('  Customize the personality, name, and instructions for your bot.\n'));

  try {
    spawnSync(editor, [claudeMd], { stdio: 'inherit' });
    pass('CLAUDE.md saved');
  } catch {
    warn(`Could not open editor -- edit ${claudeMd} manually`);
  }
}

function installSystemdService(config: Record<string, string>): void {
  console.log(bold('\n  Systemd Service\n'));

  const serviceDir = join(process.env.HOME || '/home/user', '.config/systemd/user');
  const servicePath = join(serviceDir, 'claudeclaw.service');

  mkdirSync(serviceDir, { recursive: true });

  const homeDir = process.env.HOME || '/home/user';
  const path = process.env.PATH || '/usr/local/bin:/usr/bin:/bin';

  const serviceContent = `[Unit]
Description=ClaudeClaw - Telegram Bot wrapping Claude Code CLI
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_ROOT}
ExecStart=/usr/bin/node ${PROJECT_ROOT}/dist/index.js
Restart=always
RestartSec=10
Environment=HOME=${homeDir}
Environment=PATH=${path}
Environment=NODE_ENV=production
Environment=TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN || ''}
${config.ALLOWED_CHAT_ID ? `Environment=ALLOWED_CHAT_ID=${config.ALLOWED_CHAT_ID}` : '# ALLOWED_CHAT_ID not set yet'}
${config.GROQ_API_KEY ? `Environment=GROQ_API_KEY=${config.GROQ_API_KEY}` : '# GROQ_API_KEY not configured'}
${config.GOOGLE_API_KEY ? `Environment=GOOGLE_API_KEY=${config.GOOGLE_API_KEY}` : '# GOOGLE_API_KEY not configured'}

[Install]
WantedBy=default.target
`;

  writeFileSync(servicePath, serviceContent);
  pass(`Service file written to ${servicePath}`);

  try {
    execSync('systemctl --user daemon-reload', { stdio: 'pipe' });
    pass('systemd daemon reloaded');

    execSync('systemctl --user enable claudeclaw.service', { stdio: 'pipe' });
    pass('Service enabled');

    // Don't auto-start -- need to build first
    warn('Service NOT started yet -- run "npm run build" first, then:');
    console.log(dim('    systemctl --user start claudeclaw'));
  } catch (err: any) {
    warn(`Could not configure systemd: ${err.message}`);
    console.log(dim('    You can start manually with: npm run dev'));
  }
}

async function main(): Promise<void> {
  banner();

  console.log(bold('  Checking prerequisites...\n'));
  const prereqOk = checkPrerequisites();
  if (!prereqOk) {
    console.log(red('\n  Fix the issues above and re-run setup.\n'));
    process.exit(1);
  }

  const rl = createInterface();

  try {
    const config = await collectConfig(rl);
    writeEnvFile(config);
    openEditor();
    installSystemdService(config);

    console.log(bold('\n  Setup Complete!\n'));
    console.log(`  Next steps:`);
    console.log(dim('    1. npm run build'));
    console.log(dim('    2. systemctl --user start claudeclaw'));
    console.log(dim('    3. Send /chatid to the bot on Telegram'));
    console.log(dim('    4. Set ALLOWED_CHAT_ID in .env and restart'));
    console.log('');
  } finally {
    rl.close();
  }
}

main().catch(err => {
  console.error(red(`\n  Setup failed: ${err.message}\n`));
  process.exit(1);
});
